import type { Metadata } from "next";
import nextDynamic from "next/dynamic";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { getClientIp, ensureAccessLog } from "@/lib/access-log";
import { authWithTimeout } from "@/lib/auth-safe";
/* OneSignal: src/components/providers.tsx 안의 <OneSignalBridge /> — 클라이언트에서 init + login(User.id). _app.tsx 없음(App Router). */
import { Providers } from "@/components/providers";
import "./globals.css";

/**
 * AppNav는 useSearchParams()를 씁니다. 서버에서 Suspense로 감싼 채 RSC 하이드레이션할 때
 * React 19에서 #419(Suspense 경계)가 날 수 있어, 헤더만 SSR 생략(ssr: false)로 동일 플레이스홀더만 맞춥니다.
 */
const AppNav = nextDynamic(
  () => import("@/components/app-nav").then((m) => ({ default: m.AppNav })),
  {
    ssr: false,
    loading: () => <header className="h-16 border-b border-gray-200" />,
  }
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  preload: false,
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    title: "Complete CRM",
    statusBarStyle: "default",
  },
};

// layout에서 headers() 사용으로 정적 렌더 불가. 동적 렌더 명시해 빌드/런타임 오류 방지.
export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const h = await headers();
  const pathname = h.get("x-pathname") ?? "";
  const isPublicPage =
    pathname === "/login" ||
    pathname === "/signup" ||
    pathname.startsWith("/login/");

  let session: Awaited<ReturnType<typeof authWithTimeout>> = null;
  if (!isPublicPage) {
    try {
      session = await authWithTimeout();
      if (session?.user?.id) {
        // 성능: 프로덕션에서는 초기 렌더마다 DB를 치지 않도록 기본 비활성화
        if (
          process.env.NODE_ENV === "development" ||
          process.env.ENABLE_ACCESS_LOG === "true"
        ) {
          void ensureAccessLog(
            session.user.id,
            getClientIp(h),
            h.get("user-agent") ?? ""
          ).catch((e: unknown) => console.error("[AccessLog] 기록 실패:", e));
        }
      }
    } catch (e) {
      console.error("[layout] auth failed", e);
    }
  }

  return (
    <html lang="en">
      <body
        className={`${typeof geistSans?.variable === "string" ? geistSans.variable : ""} ${typeof geistMono?.variable === "string" ? geistMono.variable : ""} antialiased`}
      >
        <Providers session={session ?? undefined}>
          <AppNav />
          <main>{children}</main>
          <Toaster richColors position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
