import type { Metadata } from "next";
import { headers } from "next/headers";
import Script from "next/script";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { getClientIp, ensureAccessLog } from "@/lib/access-log";
import { authWithTimeout } from "@/lib/auth-safe";
import { Providers } from "@/components/providers";
import { AppNav } from "@/components/app-nav";
import { OneSignalUserSync } from "@/components/OneSignalUserSync";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  preload: false,
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 전역 force-dynamic은 캐시를 전부 깨서 체감 속도를 크게 떨어뜨림.
// 필요한 페이지에서만 dynamic을 사용한다.

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const h = await headers();
  const pathname = h.get("x-pathname") ?? "";
  const isPublicPage =
    pathname === "/login" ||
    pathname === "/signup" ||
    pathname.startsWith("/login/");

  let session: Awaited<ReturnType<typeof authWithTimeout>> = null;
  if (!isPublicPage) {
    try {
      session = await authWithTimeout();
      if (session?.user?.id) {
        // 성능: 프로덕션에서는 초기 렌더마다 DB를 치지 않도록 기본 비활성화
        if (
          process.env.NODE_ENV === "development" ||
          process.env.ENABLE_ACCESS_LOG === "true"
        ) {
          void ensureAccessLog(
            session.user.id,
            getClientIp(h),
            h.get("user-agent") ?? ""
          ).catch((e: unknown) => console.error("[AccessLog] 기록 실패:", e));
        }
      }
    } catch (e) {
      console.error("[layout] auth failed", e);
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js"
          strategy="lazyOnload"
        />
        <Script id="onesignal-init" strategy="lazyOnload">
          {`
            window.OneSignalDeferred = window.OneSignalDeferred || [];
            OneSignalDeferred.push(async function(OneSignal) {
              await OneSignal.init({
                appId: "${process.env.NEXT_PUBLIC_ONESIGNAL_APP_ID ?? ""}"
              });
            });
          `}
        </Script>
        <Providers session={session ?? undefined}>
          <OneSignalUserSync />
          <Suspense fallback={<header className="h-16 border-b border-gray-200" />}>
            <AppNav />
          </Suspense>
          <main>{children}</main>
          <Toaster richColors position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
