import type { Metadata } from "next";
import { headers } from "next/headers";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { getClientIp, ensureAccessLog } from "@/lib/access-log";
import { authWithTimeout } from "@/lib/auth-safe";
import { Providers } from "@/components/providers";
import { AppNav } from "@/components/app-nav";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  preload: false,
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  preload: false,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await authWithTimeout();
  if (session?.user?.id) {
    const h = await headers();
    // 접속 로그는 응답을 막지 않도록 백그라운드에서만 실행
    void ensureAccessLog(
      session.user.id,
      getClientIp(h),
      h.get("user-agent") ?? ""
    ).catch((e) => console.error("[AccessLog] 기록 실패:", e));
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers session={session ?? undefined}>
          <Suspense fallback={<header className="h-16 border-b border-gray-200" />}>
            <AppNav />
          </Suspense>
          <main>{children}</main>
          <Toaster richColors position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
